apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: {{ template "rsyslog.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: syslog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: syslog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
{{ toYaml .Values.podAnnotations | indent 8 }}
      creationTimestamp: null
      labels:
        app: syslog
    spec:
      containers:
      - image: "{{ .Values.image.rsyslog.repository }}:{{ .Values.image.rsyslog.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: syslog
        ports:
        - containerPort: 5140
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 5
      volumes:
      - persistentVolumeClaim:
          claimName: syslog
        name: varlog
